package com.ribose.jenkins.plugin.awscodecommittrigger.it.feature.pipeline

node {
    stage('Preparation') {
        checkout([
            $class: 'com.ribose.jenkins.plugin.awscodecommittrigger.it.mock.MockGitSCM',
            branches: [[name: 'refs/heads/master']],
            userRemoteConfigs: [[
                credentialsId: 'batman',
                url: 'https://git-codecommit.us-west-2.amazonaws.com/v1/repos/testjenkins'
            ]],
        ])
    }

    stage('Build') {
        sh "echo 'Build phase'"
    }

    stage('Results') {
        sh "echo 'Result phase'"
        ${EmitEvent}
    }
}
